---
all:
  hosts:
    localhost: # localhost connection parameters, used for storing configuration while transferring it between nodes
      ansible_connection: local
  vars:
    global_project_home: "~/hlf-iot-bc"
    global_domain: hlfiot
    global_chaincode_version: "1.0"
    global_orderer_count: 2
    global_channels:
      - name: common # Channel name
        participants: # Organizations, should be included in channel
          - hlfiot
          - device
        chaincode: # Chaincode params
          name: hlf_iot_cc
          lang: golang
          version: 1.0
          policy: ""
          init: '{"Args":["init"]}'
    default_hl_explorer_port: 9090
    default_hl_explorer_username: "admin"
    default_hl_explorer_password: "adminpw"

  children:
    nodes:
      hosts:
        hlfiot.hlfiot: # Describes which containers will run on this node
          node_roles:
            - root_orderer # This node will be used to generate crypto-config for other orderers
            - orderer # This node will host an orderer-service
            - peer # This node will host peers and api containers for organization
            - root_peer # This node will be used to create channels and instantiate chaincode
            - explorer # This node will serve hyperledger fabric explorer
          org: hlfiot # Organization name
          orderer_id: 0
          ansible_host: 192.168.99.131 # Real ip address or domain name of the machine
          ansible_user: support  # User with sudo access
          #ansible_private_key_file: ~/path-to-private-key # Private key to identify ourselves
          ansible_ssh_port: 22 # Specify ssh-port here, if case of it's not defaulted.
          www_port: 3001
          ca_port: 7054
          couchdb_port: 7984
          org_ou: Customer

        device.hlfiot:
          node_roles:
            - orderer
            - peer
#            - explorer
          org: device
          orderer_id: 1 # ID of orderer-service which is running on this host
          ansible_host: 192.168.99.128
          ansible_user: support
          #ansible_private_key_file: ~/path-to-private-key
          ansible_ssh_port: 22
          www_port: 3002
          ca_port: 8054
          couchdb_port: 8984
          org_ou: Supplier
  generate_vars:
    TMPL_ARTIFACTS_DIR: ./templates/artifacts
    TMPL_DOCKER_COMPOSE_DIR: ./templates/docker-compose
    ARTIFACTS_DIR: ./artifacts
    DOCKER_COMPOSE_DIR: ./docker-compose
    FABRIC_VERSION: 1.4.2
    REST_API_IMAGE: frag:latest
    NETWORK: hlfiot
